variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "pub_subnet_cidr_1" {}
variable "pub_subnet_cidr_2" {}
variable "private_subnet_cidr_1" {}
variable "private_subnet_cidr_2" {}
variable "private_data_subnet_cidr_1" {}
variable "private_data_subnet_cidr_2" {}