version: '3.9'

services:
 # nginx:
    #image: 
    #ports:
    #  - "80:80"    # by default nginx server is listening on port 80
  node-app:
    #build: 
      #context: .   #the . is the path to the Dockerfile which is similar to build: . command
      #args:
        #NODE_ENV: production
    environment:
      - ENV_NODE=production
      #- MONGO_USER=${MONGO_USER}
      #- MONGO_PASSOWRD=${MONGO_PASSWORD}
      #- SESSION_SECRET=${SESSION_SECRET}
    command: node index.js 
  #mongo:
   # environment:
   #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
   #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
