version: "3.9"
services:
  node-project:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
# adding a second docker image      
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: docuser
      MONGO_INITDB_ROOT_PASSWORD: 32docuser
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
