name: Basic build agent
on: push 
jobs:
  build-node:
    - name: Build Node 
    - runs-on: ubuntu-latest
      container: node:19.8.1
      steps:
        - run: node --version 
        - run: npm --version 
        - uses: actions/checkout@v3
        - run: dir 
